services:
  client:
    image: recipe-site/client
    build:
      context: client
      target: development
    ports:
      - 5173:5173
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on:
      - backend
  backend:
    image: recipe-site/api
    build:
      context: api
      target: builder
    depends_on:
      - mongodb
  myapplication:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - CONN_STR=mongodb://user:pass@mongodb
    command: '/bin/bash -c "sleep 5; mongosh $$CONN_STR --eval \"show dbs;\""'
    depends_on:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: